<?php
/**
 * Styles and scripts for the module 
 *
 * @package    HNG2
 * @subpackage youtube_for_editor
 * @author     Alejandro Caballero - lava.caballero@gmail.com
 */
?>

<!-- youtube link embedder for editor -->

<link rel="stylesheet" type="text/css"
      href="<?= $config->full_root_path ?>/youtube_for_editor/media/global_styles~v<?=$config->scripts_version?>.css">

<script type="text/javascript"
        src="<?= $config->full_root_path ?>/youtube_for_editor/media/global_functions~v<?=$config->scripts_version?>.js"></script>

