<?php
/**
 * Styles and scripts for the module 
 *
 * @package    BardCanvas
 * @subpackage youtube_for_bardcanvas
 * @author     Alejandro Caballero - lava.caballero@gmail.com
 *             
 * @var module $this_module
 */

use hng2_base\module;
?>

<!-- youtube link embedder for bardcanvas -->

<link rel="stylesheet" type="text/css"
      href="<?= $config->full_root_path ?>/<?= $this_module->name ?>/media/global_styles~v<?=$config->scripts_version?>.css">

<script type="text/javascript"
        src="<?= $config->full_root_path ?>/<?= $this_module->name ?>/media/global_functions~v<?=$config->scripts_version?>.js"></script>

