<?php
/**
 * Messages and other details for the button and the dialog
 *
 * @package    HNG2
 * @subpackage youtube_for_editor
 * @author     Alejandro Caballero - lava.caballero@gmail.com
 */
?>

<!-- Youtube for editor tinymce strings -->

<div id="youtube_for_editor_tinymce_strings" style="display: none;">
    <div class="title"><?= $this_module->language->tinymce_strings->title ?></div>
    <div class="caption"><?= $this_module->language->tinymce_strings->caption ?></div>
    <div class="invalid_link"><?= $this_module->language->tinymce_strings->invalid_link ?></div>
</div>
